[default]
workers = 8
max_blocking = 64
ident = "Tappd Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"

[default.core]
app_name = ""
keys_file = "/tapp/app-keys.json"
public_logs = true
public_sysinfo = true
compose_file = "/tapp/app-compose.json"

[internal]
address = "unix:/var/run/tappd.sock"
reuse = false

[external]
address = "0.0.0.0"
port = 8090

[external-https]
address = "0.0.0.0"
port = 8043

[external-https.tls]
key = "/etc/tappd/tls.key"
certs = "/etc/tappd/tls.cert"

[guest-api]
address = "vsock:0xffffffff"
port = 8000
