workers = 8
max_blocking = 64
ident = "Teepod Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"
port = 8080
kms_url = "http://127.0.0.1:8081"


[networking]
mode = "user"
net = "10.0.2.0/24"
dhcp_start = "10.0.2.10"
restrict = false

[cvm]
ca_cert = "../certs/ca.cert"
tmp_ca_cert = "../certs/tmp-ca.cert"
tmp_ca_key = "../certs/tmp-ca.key"
kms_url = "http://127.0.0.1:8081"
tproxy_url = "http://127.0.0.1:8082"
docker_registry = ""
max_disk_size = 100
cid_start = 1000
cid_pool_size = 1000

[cvm.port_mapping]
enabled = false
address = "127.0.0.1"
range = [
    { protocol = "tcp", from = 1, to = 20000 },
]

[gateway]
base_domain = "localhost"
port = 8082
tappd_port = 8083

[auth]
enabled = false
tokens = []

[supervisor]
exe = "./supervisor"
sock = "./run/supervisor.sock"
pid_file = "./run/supervisor.pid"
log_file = "./run/supervisor.log"
