[default]
workers = 8
max_blocking = 64
ident = "Teepod Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"
port = 8080

[default.limits]
bytes = "8KiB"
data-form = "2MiB"
file = "1MiB"
form = "32KiB"
json = "1MiB"
msgpack = "1MiB"
string = "8KiB"
